#!/bin/bash

# Use the repository name as the project name
PROJECT_NAME=${GITHUB_REPOSITORY##*/}

echo "::debug::project name: $PROJECT_NAME"

find -E . -type f -regex '.*(\.(ts|json)|Dockerfile|docker-build)' -maxdepth 2 | xargs sed -i "" "s/__PROJECT_NAME__/${PROJECT_NAME}/g"
find -E . -type f -regex '.*\.(md)' -maxdepth 2 | xargs sed -i "" "s/{\*\*PROJECT_NAME\*\*}/${PROJECT_NAME}/g"
find . -name package.json -maxdepth 1 | xargs sed -i "" "s/\"version\": \".*\"/\"version\": \"1.0.0\"/g"

# Cleanup
git rm -f .github/workflows/initial-bootstrapping.yaml
git rm -f script/init-repo-placeholders
