#!/usr/bin/env bash

set -e

dest_repo=$1
if [ ! -d "$dest_repo" ]; then
	echo "Directory $dest_repo DOES NOT exists."
	exit 1
fi

current_dir=$(cd -P -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)
template_repo=$(dirname "$current_dir")

# Sync scripts
mkdir -p "$dest_repo"/script
cp "$template_repo"/script/* "$dest_repo"/script

# Sync github actions and configuration
mkdir -p "$dest_repo"/.github/workflows
cp "$template_repo"/.github/*.yaml "$dest_repo"/.github
cp -n "$template_repo"/.github/renovate.json "$dest_repo"/.github/ || true
cp "$template_repo"/.github/workflows/*.yaml "$dest_repo"/.github/workflows

# Remove workflows that are no longer needed if they exist
rm -rf "$dest_repo"/.github/workflows/bootstrap-workflows.yaml
rm -rf "$dest_repo"/.github/workflows/initial-bootstrapping.yaml

# Sync configuration files
cp "$template_repo"/.commitlintrc.yaml "$dest_repo"/
cp "$template_repo"/.pre-commit-config.yaml "$dest_repo"/
cp "$template_repo"/.releaserc.json "$dest_repo"/
cp "$template_repo"/.npmrc "$dest_repo"/
cp "$template_repo"/.yarnrc "$dest_repo"/

cp -n "$template_repo"/.nvmrc "$dest_repo"/ || true
