name: CI

on:
  workflow_dispatch:
  push:

jobs:
  release-notes:
    name: Release notes preview
    runs-on: [self-hosted, general-ubuntu]
    if: github.ref != 'refs/heads/main'
    steps:
      - uses: open-turo/actions-release/release-notes-preview@v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          extra-plugins: |
            @open-turo/semantic-release-config@1.3.0
  build:
    name: Build
    runs-on: [self-hosted, general-ubuntu]
    env:
      NPM_AUTH_TOKEN: ${{ secrets.ARTIFACTORY_NPM_AUTH_TOKEN }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Setup tools
        uses: open-turo/action-setup-tools@v1
      - name: Install yarn dependencies
        run: yarn --frozen-lockfile
      - name: Yarn Build
        run: yarn build
  lint:
    name: Lint
    runs-on: [self-hosted, general-ubuntu]
    steps:
      - uses: open-turo/actions-node/lint@v4
        with:
          github-token: ${{ secrets.TURO_GITHUB_TOKEN }}
          npm-auth-token: ${{ secrets.ARTIFACTORY_NPM_AUTH_TOKEN }}
          internal-dependency-prefixes: "@turo"
  test:
    needs: build
    name: Test
    runs-on: [self-hosted, general-ubuntu]
    steps:
      - uses: open-turo/actions-node/test@v4
        with:
          npm-auth-token: ${{ secrets.ARTIFACTORY_NPM_AUTH_TOKEN }}
          test-flags: --coverage
      - name: Upload coverage
        uses: coverallsapp/github-action@v2
        env:
          COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}
