name: Update dependencies - Auto approve

on:
  pull_request_target:
    types:
      - opened
jobs:
  auto-approve:
    name: auto-approve
    runs-on: [self-hosted, general-ubuntu]
    steps:
      - uses: hmarr/auto-approve-action@v3
        if: github.actor == 'turo-dependency-manager' && contains(github.event.pull_request.title, 'chore')
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
