name: Update dependencies
concurrency: update-dependencies

on:
  schedule:
    # Every day at midnight
    - cron: "0 0 * * *"
  workflow_dispatch:
  issue_comment:
    types:
      - edited
  pull_request:
    types:
      - edited

jobs:
  update-dependencies:
    runs-on: [self-hosted, general-ubuntu]
    name: Update dependencies
    steps:
      - name: Update dependencies
        uses: open-turo/action-renovate@v1
        with:
          github-token: ${{ secrets.TURO_GITHUB_DEPENDENCY_MANAGER_TOKEN }}
          npm-password: ${{ secrets.RENOVATEBOT_JFROG_PASSWORD }}
          npm-registry: https://turo.jfrog.io/turo/api/npm/npm/
          npm-scope: "@turo"
          npm-token: ${{ secrets.ARTIFACTORY_NPM_AUTH_TOKEN }}
          npm-username: ${{ secrets.RENOVATEBOT_JFROG_USERNAME }}
